FROM amd64/python:3.6-stretch
WORKDIR /usr/src/build

ENV PYTHONUNBUFFERED 1

RUN apt update
RUN apt install -y devscripts build-essential:native python3-all python3-setuptools

COPY . /usr/src/build
CMD debuild -i -us -uc -b && \
    cp -v ../*.deb /usr/src/deb/
