FROM debian
WORKDIR /usr/src/build

ENV PYTHONUNBUFFERED 1

RUN apt update
RUN apt install -y devscripts crossbuild-essential-armhf binutils-multiarch build-essential:native python3-all python3-setuptools
RUN apt install -y python3-all python3-setuptools
COPY . /usr/src/build
CMD debuild  -aamd64 -i -us -uc -b && \
    cp -v ../*.deb /usr/src/deb/
