version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:18.03.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              python3 py3-pynacl py3-cffi py3-bcrypt py3-cryptography
            python3 -m ensurepip
            pip3 install docker-compose
      - run:
          name: Build application Docker image
          command: |
            docker-compose build
      - run:
          name: Run application Docker image
          command: |
            docker-compose up
      - store_artifacts:
          path: /tmp/deb
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              package_cloud push wott/python-iptables/debian/stretch /tmp/deb/*.deb
              package_cloud push wott/python-iptables/raspbian/stretch /tmp/deb/*.deb
            fi


#apt install devscripts crossbuild-essential-armhf binutils-multiarch
#
#apt install python3-all
#debuild -aamd64 -i -us -uc -b
#
#apt install python3-all:i386
#ln -s `which objcopy` /usr/bin/i686-linux-gnu-objcopy
#ln -s `which strip` /usr/bin/i686-linux-gnu-strip
#debuild   --set-envvar LDSHARED="$(which gcc) -pthread -shared"  --set-envvar CC=`which gcc` --set-envvar CFLAGS="-m32" -ai386 -i -us -uc -b
#
#apt install -y python3-all:armhf python3:armhf
#debuild -aarmhf -i -us -uc -b
